# Generated by Django 2.1.3 on 2019-01-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='view_count',
            field=models.PositiveIntegerField(default=10, verbose_name='Просмотры'),
        ),
    ]
