# Generated by Django 2.1.3 on 2019-01-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item_view_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemimage',
            options={'ordering': ('priority',), 'verbose_name': 'Фото товара', 'verbose_name_plural': 'Фотки товара'},
        ),
        migrations.AddField(
            model_name='itemimage',
            name='priority',
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
    ]
