# Generated by Django 2.1.3 on 2019-09-21 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190226_1637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacture',
            options={'verbose_name': 'Производство', 'verbose_name_plural': 'Производство'},
        ),
        migrations.RemoveField(
            model_name='banner',
            name='image_title_en',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='image_title_kz',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='image_title_ru',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='subtitle_en',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='color',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='item',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='item',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='manufacture',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='size',
            name='name_en',
        ),
        migrations.AlterField(
            model_name='banner',
            name='image_title',
            field=models.CharField(max_length=500, verbose_name='Относительная ссылка на категорию или товар'),
        ),
        migrations.AlterField(
            model_name='item',
            name='manufacture',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Manufacture'),
        ),
    ]
