# Generated by Django 2.1.3 on 2019-09-21 17:55

from django.db import migrations, models
import django.db.models.deletion
import nakey.utils.upload


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190921_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to=nakey.utils.upload.banner_upload, verbose_name='Картинка на фоне'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='subtitle',
            field=models.CharField(blank=True, max_length=500, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='subtitle_kz',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='subtitle_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(blank=True, max_length=500, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title_kz',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='item',
            name='manufacture',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Manufacture', verbose_name='Пройзводство'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.PositiveIntegerField(blank=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sizes',
            field=models.ManyToManyField(blank=True, to='core.Size', verbose_name='Размер'),
        ),
    ]
