# Generated by Django 2.1.3 on 2019-10-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190921_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='show_price',
            field=models.BooleanField(default=True),
        ),
    ]
