# Generated by Django 2.1.3 on 2019-10-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_item_show_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='show_manufacture',
            field=models.BooleanField(default=True, verbose_name='Показать пройзводство'),
        ),
        migrations.AlterField(
            model_name='item',
            name='show_price',
            field=models.BooleanField(default=True, verbose_name='Показать цену'),
        ),
    ]
